---
- name: Debian/Ubuntu NodeJS debsource repo
  block:

  - name: Ensure the node repository key has been imported [Debian]
    apt_key:
      url: "{{ rocket_chat_node_apt_key }}"
    tags: repo

  - name: Ensure the node repository is present [Debian]
    apt_repository:
      repo: "{{ rocket_chat_node_apt_repo }}"
      state: present
    tags: repo
    register: rocket_chat_node_repo_state

  when:
    - (rocket_chat_node_apt_repo is defined)
    - (rocket_chat_node_apt_repo)
    - ((ansible_os_family | lower) == "debian")

- name: RHEL-based NodeJS debsource repo
  block:

  - name: Ensure the node repository key has been imported [RHEL]
    rpm_key:
      key: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
    tags: repo

  - name: Ensure the node repository is present [RHEL]
    yum_repository:
      name: "{{ nodejs }}"
      baseurl: "{{ rocket_chat_node_rpm_repo.baseurl }}"
      state: present
      description: "{{ rocket_chat_node_rpm_repo.desc }}"
      gpgcheck: "{{ rocket_chat_node_rpm_repo.gpgcheck }}"
      gpgkey:  "{{ rocket_chat_node_rpm_repo.pgp_key }}"
    tags: repo
    register: rocket_chat_node_repo_state

  when:
    - (rocket_chat_node_rpm_repo is defined)
    - (rocket_chat_node_rpm_repo)
    - ((ansible_os_family | lower) == "redhat")

- name: Ensure NodeJS installed
  package:
    name: nodejs
